displayName=Iron Stock Sync
author=hpuf
description=Captures Ironman bank stock for a personal progression tracker
tags=ironman,bank,tracker
version=
plugins=com.hpuf.ironstocksync.IronStockSyncPlugin
build=standard
